services:
  campaign-service:
    image: saransh76/campaign-service:latest
    container_name: campaign-service
    ports:
      - "8006:8006"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - microservices-network

networks:
  microservices-network:
    external: true